# Generated by Django 5.2.11 on 2026-02-27 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_paillotte_sucree_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMenuEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('space_key', models.CharField(max_length=64)),
                ('section', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=255)),
                ('fiche_product_id', models.UUIDField(blank=True, null=True)),
                ('expected_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_menu_entries', to='core.site')),
            ],
            options={
                'db_table': 'core_service_menu_entry',
                'ordering': ['service_date', 'space_key', 'sort_order', 'title'],
                'indexes': [models.Index(fields=['site', 'service_date'], name='idx_core_srv_site_date'), models.Index(fields=['fiche_product_id'], name='idx_core_srv_fiche')],
            },
        ),
    ]
