# Generated by Django 5.2.11 on 2026-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicemenuentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemenuentry',
            name='expected_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
