# Generated by Django 5.2.11 on 2026-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
