from django.urls import path
from rest_framework.routers import DefaultRouter

from apps.integration.api.v1.haccp_views import (
    HaccpColdPointDetailView,
    HaccpColdPointSyncView,
    HaccpColdPointListView,
    HaccpLabelProfileDetailView,
    HaccpLabelProfileListCreateView,
    HaccpLabelSessionListCreateView,
    HaccpLifecycleEventListView,
    HaccpOcrQueueView,
    HaccpOcrValidateView,
    HaccpSiteSyncView,
    HaccpSectorDetailView,
    HaccpSectorListView,
    HaccpSectorSyncView,
    HaccpTemperatureReadingListView,
    HaccpTracciaReconciliationOverviewView,
    HaccpScheduleDetailView,
    HaccpScheduleListCreateView,
)
from apps.integration.api.v1.views import (
    DriveAssetImportView,
    DocumentClaudeExtractView,
    DocumentExtractionViewSet,
    DocumentIngestViewSet,
    TraceabilityReconciliationDecisionListCreateView,
    DocumentReviewView,
    FicheCatalogImportView,
    FicheSnapshotEnvelopeImportView,
    FicheSnapshotImportView,
    FicheRecipeTitleListView,
    IntegrationDocumentViewSet,
    TracciaAssetImportView,
)


router = DefaultRouter()
router.register("integration/documents", IntegrationDocumentViewSet, basename="integration-document")

urlpatterns = [
    path(
        "integration/fiches/catalog/import/",
        FicheCatalogImportView.as_view(),
        name="integration-fiches-catalog-import",
    ),
    path(
        "integration/fiches/snapshots/import/",
        FicheSnapshotImportView.as_view(),
        name="integration-fiches-snapshot-import",
    ),
    path(
        "integration/fiches/snapshots/import-envelope/",
        FicheSnapshotEnvelopeImportView.as_view(),
        name="integration-fiches-snapshot-envelope-import",
    ),
    path(
        "integration/fiches/recipe-titles/",
        FicheRecipeTitleListView.as_view(),
        name="integration-fiches-recipe-titles",
    ),
    path(
        "integration/traccia-assets/import/",
        TracciaAssetImportView.as_view(),
        name="integration-traccia-asset-import",
    ),
    path(
        "integration/drive-assets/import/",
        DriveAssetImportView.as_view(),
        name="integration-drive-asset-import",
    ),
    path(
        "integration/documents/<uuid:document_id>/extractions/",
        DocumentExtractionViewSet.as_view({"post": "create"}),
        name="integration-document-extraction-create",
    ),
    path(
        "integration/documents/<uuid:document_id>/ingest/",
        DocumentIngestViewSet.as_view({"post": "create"}),
        name="integration-document-ingest-create",
    ),
    path(
        "integration/documents/<uuid:document_id>/extract-claude/",
        DocumentClaudeExtractView.as_view(),
        name="integration-document-claude-extract",
    ),
    path(
        "integration/documents/<uuid:document_id>/review/",
        DocumentReviewView.as_view(),
        name="integration-document-review",
    ),
    path(
        "integration/reconciliation-decisions/",
        TraceabilityReconciliationDecisionListCreateView.as_view(),
        name="integration-traceability-reconciliation-decision-list-create",
    ),
    path(
        "haccp/traccia/ocr-queue/",
        HaccpOcrQueueView.as_view(),
        name="haccp-traccia-ocr-queue",
    ),
    path(
        "haccp/traccia/ocr-queue/<uuid:document_id>/validate/",
        HaccpOcrValidateView.as_view(),
        name="haccp-traccia-ocr-validate",
    ),
    path(
        "haccp/traccia/lifecycle/",
        HaccpLifecycleEventListView.as_view(),
        name="haccp-traccia-lifecycle-list",
    ),
    path(
        "haccp/traccia/sectors/",
        HaccpSectorListView.as_view(),
        name="haccp-traccia-sector-list",
    ),
    path(
        "haccp/traccia/sectors/<uuid:sector_id>/",
        HaccpSectorDetailView.as_view(),
        name="haccp-traccia-sector-detail",
    ),
    path(
        "haccp/traccia/sites/sync/",
        HaccpSiteSyncView.as_view(),
        name="haccp-traccia-site-sync",
    ),
    path(
        "haccp/traccia/sectors/sync/",
        HaccpSectorSyncView.as_view(),
        name="haccp-traccia-sector-sync",
    ),
    path(
        "haccp/traccia/cold-points/",
        HaccpColdPointListView.as_view(),
        name="haccp-traccia-cold-point-list",
    ),
    path(
        "haccp/traccia/cold-points/<uuid:point_id>/",
        HaccpColdPointDetailView.as_view(),
        name="haccp-traccia-cold-point-detail",
    ),
    path(
        "haccp/traccia/cold-points/sync/",
        HaccpColdPointSyncView.as_view(),
        name="haccp-traccia-cold-point-sync",
    ),
    path(
        "haccp/traccia/temperature-readings/",
        HaccpTemperatureReadingListView.as_view(),
        name="haccp-traccia-temperature-reading-list",
    ),
    path(
        "haccp/traccia/reconciliation-overview/",
        HaccpTracciaReconciliationOverviewView.as_view(),
        name="haccp-traccia-reconciliation-overview",
    ),
    path(
        "haccp/schedules/",
        HaccpScheduleListCreateView.as_view(),
        name="haccp-schedule-list-create",
    ),
    path(
        "haccp/schedules/<uuid:schedule_id>/",
        HaccpScheduleDetailView.as_view(),
        name="haccp-schedule-detail",
    ),
    path(
        "haccp/label-profiles/",
        HaccpLabelProfileListCreateView.as_view(),
        name="haccp-label-profile-list-create",
    ),
    path(
        "haccp/label-profiles/<uuid:profile_id>/",
        HaccpLabelProfileDetailView.as_view(),
        name="haccp-label-profile-detail",
    ),
    path(
        "haccp/label-sessions/",
        HaccpLabelSessionListCreateView.as_view(),
        name="haccp-label-session-list-create",
    ),
]

urlpatterns += router.urls
