# Generated by Django 5.2.11 on 2026-03-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_traceability_reconciliation_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationdocument',
            name='document_type',
            field=models.CharField(choices=[('goods_receipt', 'goods_receipt'), ('invoice', 'invoice'), ('label_capture', 'label_capture')], max_length=32),
        ),
        migrations.AlterField(
            model_name='integrationdocument',
            name='source',
            field=models.CharField(choices=[('upload', 'upload'), ('email', 'email'), ('api', 'api'), ('drive', 'drive')], default='upload', max_length=16),
        ),
        migrations.AlterField(
            model_name='integrationdocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('extracted', 'extracted'), ('failed', 'failed'), ('archived_duplicate', 'archived_duplicate')], default='uploaded', max_length=24),
        ),
    ]
